>BAC56009
ID   Q84Z97      PRELIMINARY;      PRT;   594 AA.
AC   Q84Z97;
DT   01-JUN-2003 (TrEMBLrel. 24, Created)
DT   01-JUN-2003 (TrEMBLrel. 24, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   P0705A05.28 protein.
GN   P0705A05.28.
OS   Oryza sativa (japonica cultivar-group).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=39947;
RN   [1]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Sasaki T., Matsumoto T., Yamamoto K.;
RT   "Oryza sativa nipponbare(GA3) genomic DNA, chromosome 8, PAC
RT   clone:P0705A05.";
RL   Submitted (JAN-2002) to the EMBL/GenBank/DDBJ databases.
DR   EMBL; AP004623; BAC56009.1; -.
SQ   SEQUENCE   594 AA;  65899 MW;  68B1645C3FE0A357 CRC64;
     MASPPPPPRL LTPKPDPDAP LPPLPYPDPN LVQSMLFSAQ SPQAQPQAPP PHIQPPASAS
     AEAPSGDEKN KKKKKRARAS QEMVRITNLS IADHLHYRSL VRRARLTFEA LRAIYQRQDL
     ATAGGIRNRF DLRASSKMLS KGLWMHRDIR TVGSIPGLLV GDSFFYRAEL CVLGLHTAPQ
     AGIGYIPASI VDQGHPVATS IVSSGGYLDD EDSGDVLVYS GSGGRLRNRL DHSADQTLQR
     GNLALHYSCH YGIEVRVIRG HACDHSPSSK VYVYDGLYRV VTSTFGPGKS GRDVCKFKLV
     RIPGQDDLGS KAWHTAAELK DALDSKIRPP KYISLDIAKG KEPFRVPLYN KLDDDRSPLF
     YDYIACPDFP TTQQLLKRQT QRGCHCAELC GSRCSCERKN RGADGPVYTS DGILLRGRPL
     VYECGPLCGC PMTCPNRVTQ QGMKHRLEVF RSKETGWGVR TLDLIQPGAF ICEYAGDVLS
     LDSHSGDAPL PPMEDGSSII DPTKFPERWR EWGDASVVYP DRVPHFPLFA GARYRLDVSQ
     RRNVACYISH SCSPNVFLQY VIRGNEDESY PHMMVFAMET IPPMRDLSID YGLD
//
>CAD18871
ID   Q84UI6      PRELIMINARY;      PRT;   895 AA.
AC   Q84UI6;
DT   01-JUN-2003 (TrEMBLrel. 24, Created)
DT   01-JUN-2003 (TrEMBLrel. 24, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   Enhancer of zeste protein.
GN   EZ1.
OS   Oryza sativa (indica cultivar-group).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=39946;
RN   [1]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Pusa basmati;
RA   Thakur J.K., Malik M., Tyagi A.K., Khurana J.P.;
RT   "A polycomb group gene (OsPCG1)from rice.";
RL   Submitted (DEC-2001) to the EMBL/GenBank/DDBJ databases.
DR   EMBL; AJ421722; CAD18871.3; -.
SQ   SEQUENCE   895 AA;  99775 MW;  BB618FCD0E414FA2 CRC64;
     MASSSSKASD SSSQRPKRPD QGPSGKDAAG LVVLHGKLAQ LKRQVQSTRL AAIKERVEAN
     RKALQVHTCA LFDVAAAAEV ASRGAEGGNA LSRGAAEGHC RLVGWDSASG PGERELVHVQ
     EENLVAGTLV LSSSGGSGAS HRTVVQLAKL PVVDKIPPYT TWIFLDKNQR MADDQLVCRR
     RIYYDPIVNE ALICSESDDD VPEPEEEKHV FTEGEDQLIW KATQDHGLSR EVLNVLCQFV
     DATPSEIEER SEVLFEKYEK QSQSSYETDF QLFLGKTMDV ALDSFDNLFC RRCLVFDCRL
     HGCSQNLVFP SEKQPYGHGL DENKRPCGDQ RYLRRREVYQ DTCNDDRNAC TTYNTDSRSS
     SLKVSATILS ESEDSNRDED NIKSTSIVET SRSKITNSEY ADKSVTPPPG DASETENVSP
     DMPLRTLGRR KISKHASKSN DHSPDKRQKI YSSPFPFAMS VLNKQSVPEI GETCPDSIES
     AVDQLPSLDD PNKKISTKDM CAGSTTNTTE NTLRDNNNNL FISNKEHSIS HWSALERDLY
     LKGIEIFGKN SCLIARNLLS GLKTCMEVAS YMYNNGAAMA KRPLSGKSIL GDFAEAEQGY
     MEQDLVARTR ICRRKGRARK LKYTWKSAGH PTVRKRIGDG KQWYTQYNPC GCQQMCGKDC
     ACVENGTCCE KYCGCSKSCK NRFRGCHCAK SQCRSRQCPC FAASRECDPD VCRNCWVSCG
     DGSLGEPLAR GDGYQCGNMK LLLKQQQRIL LGKSDVAGWG AFIKNPVNRN DYLGEYTGEL
     ISHREADKRG KIYDRANSSF LFDLNEQYVL DAYRKGDKLK FANHSSNPNC YAKVMLVAGD
     HRVGIYAKDR IEASEELFYD YRYGPDQAPA WARRPEGSKK DEASVSHHRA HKVAR
//
>Q8GTZ5
ID   Q8GTZ5      PRELIMINARY;      PRT;   793 AA.
AC   Q8GTZ5;
DT   01-MAR-2003 (TrEMBLrel. 23, Created)
DT   01-MAR-2003 (TrEMBLrel. 23, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   Putative TPR (Tetratricopeptide repeat) domain containing
DE   protein.
GN   OSJNBA0062C05.29.
OS   Oryza sativa (japonica cultivar-group).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=39947;
RN   [1]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Buell C.R., Yuan Q., Ouyang S., Liu J., Gansberger K., Jones K.M.,
RA   Overton II L.L., Tsitrin T., Kim M.M., Bera J.J., Jin S.S.,
RA   Fadrosh D.W., Tallon L.J., Koo H., Zismann V., Hsiao J., Blunt S.,
RA   Vanaken S.S., Riedmuller S.B., Utterback T.T., Feldblyum T.V.,
RA   Yang Q.Q., Haas B.J., Suh B.B., Peterson J.J., Quackenbush J.,
RA   White O., Salzberg S.L., Fraser C.M.;
RT   "Oryza sativa chromosome 10 BAC OSJNBa0062C05 genomic sequence.";
RL   Submitted (SEP-2002) to the EMBL/GenBank/DDBJ databases.
DR   EMBL; AC084023; AAN05556.1; -.
DR   InterPro; IPR001214; SET.
DR   InterPro; IPR001440; TPR.
DR   Pfam; PF00515; TPR; 4.
DR   SMART; SM00028; TPR; 4.
DR   PROSITE; PS50280; SET; 1.
SQ   SEQUENCE   793 AA;  87543 MW;  450FA11B56649D41 CRC64;
     MERLKSAVPA ELRRAVGEGT AADLPSTTSR LLAFLEALPL FRQVIGELTD PELALCRKDK
     GRAAELKGKG NACFSKREFE QALGFYSQAL RYFPISPDGT DASLIATLYV NRASTMHKLG
     LLEECLRDCD RAISVSPNYA KAWYRRGMVN ASFRNYSSSI HDLEVALSME VTSSGKSNIE
     QELKLILQKH QNVNEVGTAS SNCINADMPH TEQQPKVILE CTSTPNKGRG MSSPNDISPA
     SLIHAEDPLA VIIMKSCRDT HCHYCFSEAP ADVVVCPSCT IPIYCSNRCQ EKAIGQMSCN
     QNTHLESNNN VVDIAKLSVT STKSKTPDSK QIAEHRHECG GACWAAVLPA DIVLAGRIMA
     QYIEKQLLVG KRSTISGPNL DLVHHYDQDS SASKFESHIY ATVLFLCLQS YYKSGVSWAE
     DSLSQLVLLI CQIKVNSIAI VHMKSMDGVK ALTKGFSGFS GDVMCSVEQV RVAQAIYMSG
     SFFNHSCRPN IHAYFHSRTL ILRSTEYIKA GSPIELSYGP QVGEMDLPER QKSLRENYYF
     SCGCSSCSVL SLSDLVMNSF CCPQSNCLGA VSELIHHRHK ENFVHVSIGE SHVCTLSLPD
     VSKFDEDIVK VGKLFFKSDT MFNIDPGFCM SCRSQLDLSS AVAMSDRATS KINRLKELPS
     LDNVPEVLIA EALQSLERIE KLRHPYSKTL AQSHDTIAEA FAKVGDQEQA RKHCEASIKI
     LEKLYHPRHI IIAHELIKLV SIELSMGDGA SAAAAFARAD AIFSLYYGPD VERILPYVDV
     LRRTVSERSI DSC
//
>Q8H2G7
ID   Q8H2G7      PRELIMINARY;      PRT;  1015 AA.
AC   Q8H2G7;
DT   01-MAR-2003 (TrEMBLrel. 23, Created)
DT   01-MAR-2003 (TrEMBLrel. 23, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   Putative curly leaf protein.
GN   P0676F10.33.
OS   Oryza sativa (japonica cultivar-group).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=39947;
RN   [1]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Sasaki T., Matsumoto T., Yamamoto K.;
RT   "Oryza sativa nipponbare(GA3) genomic DNA, chromosome 6, PAC
RT   clone:P0676F10.";
RL   Submitted (OCT-2002) to the EMBL/GenBank/DDBJ databases.
DR   EMBL; AP005813; BAC20634.1; -.
DR   InterPro; IPR001214; SET.
DR   Pfam; PF00856; SET; 1.
DR   SMART; SM00317; SET; 1.
DR   PROSITE; PS50280; SET; 1.
SQ   SEQUENCE   1015 AA;  113086 MW;  DBD078A417D199FF CRC64;
     MEPGQLPMVA RRCIRHQQST SRLMSVAWSA MRPALRPMSL VRPTPFTAPS VSTCPVAMAC
     CAASTAVWNP NEPPLLDLTV DCRRAAHHVV PTAVGVGRRR SRGGAGGRGC RRWASEGGAW
     KLVLSPQPMF CEEGSSESGY VLCVIDSLKK KITSDRFVYI QKRVEENSIK LSPITLHSHN
     LSKNRQTSTS NSTDLVSNLL TKRKEDALCA VNSRESSPDE SEGANCQDEC SSTVIVGGNL
     SARNSVRPIR LPEVATLPPY TTWIFLDRNQ RMQEDQSVLG RRRIYYDTNC GEALICSDSE
     DEAVEDEEEK KEFKDSEDCI IRMTIQECGM SDAVLETLAR DIERAPDDIK ARYEILQGEK
     PEGSSKKVSE LNVKMEDVYG DKDLDAALDS FDNLFCRRCL VFDCKLHGCS QDLVFPTEKQ
     APLCSSDEGT PCGIHCYKLV SKPDAIMEID SHLLVDVEEP TSDNLKDQIG SNKKKLGSSG
     QKTKSQQSES SSTARVSSES SESEVQLLSN KSPQHSPGLS KNKLGAKGGI KKSTNRRIAE
     RILMSVKKGQ QEMSPDSNSI VNGCHWPRDM KLRSDTRSGI KDSVVSSQCN SPSTRSFRKK
     GTLQMENNSS FVDAQSDSME DTNNEHSATD GCDSSRKEEC VDESICRQEA HGRSWKVIEQ
     GLLLKGLEIF GKNSCLIARN LLGGMKTCTD VFQYMNYIEN SSASGALSGV DSLVKGYMKG
     NELRTRSRFV RRRGRVRRLK YTWKTAGYHF IRKRITERKD QPCRQYTPCG CQSACGKQCP
     CLTNGTCCEK YCGCPKMCKN RFRGCHCAKS QCRSRQCPCF AADRECDPDV CRNCWVGCGD
     GTLGVPNQRG DNYECRNMKL LLKQQQRVLL GRSDVSGWGA FLKNSVGKHE YLGEYTGELI
     SHKEADKRGK IYDRENSSFL FNLNNEYVLD AYRMGDKLKF ANHSPDPNCY AKVIMVAGDH
     RVGIFAKERI SAGEELFYDY RYEPDRAPAW ARKPEGPGAK DDAQPSTGRA KKLAH
//
>Q8LHD6
ID   Q8LHD6      PRELIMINARY;      PRT;   385 AA.
AC   Q8LHD6;
DT   01-OCT-2002 (TrEMBLrel. 22, Created)
DT   01-OCT-2002 (TrEMBLrel. 22, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   P0458E05.13 protein.
GN   P0458E05.13.
OS   Oryza sativa (japonica cultivar-group).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=39947;
RN   [1]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Sasaki T., Matsumoto T., Yamamoto K.;
RT   "Oryza sativa nipponbare(GA3) genomic DNA, chromosome 1, PAC
RT   clone:P0458E05.";
RL   Submitted (NOV-2001) to the EMBL/GenBank/DDBJ databases.
DR   EMBL; AP004365; BAC05613.1; -.
DR   Gramene; Q8LHD6; -.
DR   GO; GO:0003677; F:DNA binding activity; IEA.
DR   GO; GO:0006355; P:regulation of transcription, DNA-dependent; IEA.
DR   InterPro; IPR001214; SET.
DR   InterPro; IPR007087; Znf_C2H2.
DR   InterPro; IPR001965; Znf_PHD.
DR   Pfam; PF00628; PHD; 1.
DR   Pfam; PF00856; SET; 1.
DR   SMART; SM00249; PHD; 1.
DR   PROSITE; PS50280; SET; 1.
DR   PROSITE; PS50016; ZF_PHD_2; 1.
DR   PROSITE; PS00028; ZINC_FINGER_C2H2_1; 1.
SQ   SEQUENCE   385 AA;  43528 MW;  8356DAEA9CA7CF83 CRC64;
     MGRRALPPSS SSSSSSSTTT TSPELRRKRT AAPPPPPSPR RYRSISDVMR RSLPVDAAPP
     VARAYESTRC DVCGSGERDE ELLLCDGCDR GRHTFCLRPI AARVPTGPWF CPPCAPRSKP
     VKRFPMTQTK IVDFFRIQKG AEDAEAEKYG LFQDVKKRRK RSLVMHKKRR RILPYVPTED
     KVQRLKQMAS LATAMTSSKM KFSNELTYMP GMAGRSCNQA TLEEGGMQIL PKEDKETIEL
     CRTMQKRGEC PPLLVVFDSR EGFTVQADAD IKDMTFIAEY TGDVDFLENR ANDDGDSIMT
     LLLTEDPSKR LVICPDKRGN ISRFINGINN HTLDGKKKKN IKCVRYDIDG ESHVLLVACR
     DIACGEKLYY DYNGYEHEYP THHFV
//
>Q8LJP4
ID   Q8LJP4      PRELIMINARY;      PRT;   970 AA.
AC   Q8LJP4;
DT   01-OCT-2002 (TrEMBLrel. 22, Created)
DT   01-OCT-2002 (TrEMBLrel. 22, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   P0489G09.11 protein.
GN   P0489G09.11.
OS   Oryza sativa (japonica cultivar-group).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=39947;
RN   [1]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Sasaki T., Matsumoto T., Yamamoto K.;
RT   "Oryza sativa nipponbare(GA3) genomic DNA, chromosome 1, PAC
RT   clone:P0489G09.";
RL   Submitted (JUL-2000) to the EMBL/GenBank/DDBJ databases.
CC   -!- SIMILARITY: CONTAINS 1 SET DOMAIN.
DR   EMBL; AP002745; BAC00543.1; -.
DR   Gramene; Q8LJP4; -.
DR   GO; GO:0003677; F:DNA binding activity; IEA.
DR   GO; GO:0006355; P:regulation of transcription, DNA-dependent; IEA.
DR   InterPro; IPR003616; PostSET.
DR   InterPro; IPR000313; PWWP_domain.
DR   InterPro; IPR001214; SET.
DR   InterPro; IPR001965; Znf_PHD.
DR   Pfam; PF00628; PHD; 1.
DR   Pfam; PF00855; PWWP; 1.
DR   Pfam; PF00856; SET; 1.
DR   SMART; SM00317; SET; 1.
DR   PROSITE; PS50868; POST_SET; 1.
DR   PROSITE; PS50812; PWWP; 1.
DR   PROSITE; PS50280; SET; 1.
DR   PROSITE; PS01359; ZF_PHD_1; UNKNOWN_1.
DR   PROSITE; PS50016; ZF_PHD_2; 1.
SQ   SEQUENCE   970 AA;  107823 MW;  30FD023F58AC3E8C CRC64;
     MLKFAASHLI PPPRADESSS PTSRLRLVPP TSRSKFSFKT RAPPCEGTQI FRPRLASEPH
     SDSPAEILKI PRPQRSETRN PNTRRIWPPT SWGEEGSSIL GFCFGAAGML ASRIPLKRCT
     AAAVVPLPGE LEMEEGPTPP AGGGEGSGAA VVPAKRRRER VVPSRFRDSV VSLPLPPAKK
     GRPAKKAAAR EGGDGEVYDV EVRAVEQQGA TAAAFGAVET AVWPGDERPA QTEEELYRAC
     RNIRRSSSSS GFSGSVVTSL SNAGGSVAPE GKPVVVVECK PKREGGDKKE DFYWPEDFVL
     GDVVWARSGK KCPAWPAVVI DPLLHAPAVV LNSCIPGALC VMFFGFSSGG HGRDYGWIKQ
     GMIFPFVDYL DRFQGQALYK LKANRFRQAI EEAFLAERGF CELEMDEGCS LEKSVNDQSV
     PDGLQEGSGS NNDQECQSEA QVVGKSTGCC DSCGNRVPPK IAKKKKQAGE QLLCRHCDKL
     LQSKQYCGIC KKIWHHTDGG NWVCCDECQI WVHVECDLTC INMEDLENAD YFCPDCKSKR
     KTVPPVEQMN TPNSSEILCQ CNSCKERLMS LSEWERHTGS RKKNWKMSVK LKSNGDPLVT
     LTFSFLIALG GALKPTDIDQ LWVHVTCAWF QPKVSFPVDE TMEPAMGILS IPSEYFKKAC
     VICKQMHGAC TQCYKCSTYY HAMCASRAGY RMEWHKFVLL TPVLLTLCST PDPDNVLIVK
     TPEGVFSTKF LPQNNEKQSG TRLVRKENLQ EKVLPAKISD CPAARCLPYE MLKNKKEPGE
     AIAHRIMGPR HHSQESIEGL NACMDQKDEK SFATFRERLR YLQKIENKRV SCGRSGIHGW
     GLFAAKKIQE GQMVIEYRGD QVRRSVADLR EARYHREKKD CYLFKISEDV VVDATEKGNI
     ARLINHSCMP NCYARIMSVG DEKSQIILIA KRDVSAGEEL TYDYLFDPDE SEDCRVPCLC
     KALNCRGYMN
//
>Q8LLD6
ID   Q8LLD6      PRELIMINARY;      PRT;   895 AA.
AC   Q8LLD6;
DT   01-OCT-2002 (TrEMBLrel. 22, Created)
DT   01-OCT-2002 (TrEMBLrel. 22, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   SET domain-containing protein.
GN   SET1.
OS   Oryza sativa (Rice).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=4530;
RN   [1]
RP   SEQUENCE FROM N.A.
RA   Liang Y.-K., Wang Y., Zhang Y., Li S.-G., Lu X.-C., Xu Z.-H.,
RA   Bai S.-N.;
RT   "OsSET1, a novel SET-domain containing gene from rice.";
RL   Submitted (AUG-2001) to the EMBL/GenBank/DDBJ databases.
CC   -!- SIMILARITY: CONTAINS 1 SET DOMAIN.
DR   EMBL; AF407010; AAN01115.1; -.
DR   Gramene; Q8LLD6; -.
DR   InterPro; IPR001214; SET.
DR   InterPro; IPR008197; WAP.
DR   Pfam; PF00856; SET; 1.
DR   SMART; SM00317; SET; 1.
DR   PROSITE; PS00317; 4_DISULFIDE_CORE; 1.
DR   PROSITE; PS50280; SET; 1.
SQ   SEQUENCE   895 AA;  99800 MW;  47AA0F5DBFB7C84F CRC64;
     MASSSSKASD SSSQRPKRPD QGPSGKDAAG LVALHGKLAQ LKRQVQSTRL AAIKERVEAN
     RKALQVHTCA LFDVAAAAEV ASRGAEGGNA LSRGAAEGHR RFVGWDSASG PGERELVHVQ
     EENLVAGTLV LSSSGGSGAS HRTVVQLVKL PVVDKIPPYT TWIFLDKNQR MADDQSVGRR
     RIYYDPIVNE ALICSESDDD VPEPEEEKHV FTEGEDQLIW KATQDHGLSR EVLNVLCQFV
     DATPSEIEER SEVLFEKYEK QSQSSYKTDL QLFLDKTMDV ALDSFDNLFC RRCLVFDCRL
     HGCSQNLVFP SEKQPYGHEL DENKRPCGDQ CYLRRREVYQ DTCNDDRNAC TTYNMDSRSS
     SLKVSATILS ESEDSNRDED NIKSTSIVET SRSKITNSEY ADKSVTPPPG DASETENVSP
     DMPLRTLGRR KISKHASKSN DHSPDKRQKI YSSPFPFAMS VLNKQSVPEI GETCPDSIES
     AVDQLPSLDD PNKKISTKDM CAGSTTNTTE NTLRDNNNNL FISNKEHSIS HWSALERDLY
     LKGIEIFGKN SCLIARNLLS GLKTCMEVAS YVYNNGAAMA KRPLSGKSIL GDFAEAEQGY
     MEQDLVARTR ICRRKGRARK LKYTWKSAGH PTVRKRIGDG KQWYTQYNPC GCQQMCGKDC
     ACVENGTCCE KYCGCSKSCK NRFRGCHCAK SQCRSRQCPC FAASRECDPD VCRNCWVSCG
     DGSLGEPPAR GDGYQCGNMK LLLKQQQRIL LGKSDVAGWG AFIKNPVNRN DYLGEYTGEL
     ISHREADKRG KIYDRANSSF LFDLNEQYVL DAYRKGDNLK FANHSSNPNC YAKVMLVAGD
     HRVGIYAKDR IEASEELFYD YRYGPDQAPA WARRPEGSKK DEASVSHHRA HKVAR
//
>Q8LN53
ID   Q8LN53      PRELIMINARY;      PRT;   425 AA.
AC   Q8LN53;
DT   01-OCT-2002 (TrEMBLrel. 22, Created)
DT   01-OCT-2002 (TrEMBLrel. 22, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   Hypothetical protein (Fragment).
GN   OSJNBA0004G17.3.
OS   Oryza sativa (japonica cultivar-group).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=39947;
RN   [1]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Buell C.R., Yuan Q., Ouyang S., Liu J., Gansberger K., Jones K.M.,
RA   Overton II L.L., Tsitrin T., Kim M.M., Bera J.J., Jin S.S.,
RA   Fadrosh D.W., Tallon L.J., Koo H., Zismann V., Hsiao J., Blunt S.,
RA   Vanaken S.S., Riedmuller S.B., Utterback T.T., Feldblyum T.V.,
RA   Yang Q.Q., Haas B.J., Suh B.B., Peterson J.J., Quackenbush J.,
RA   White O., Salzberg S.L., Fraser C.M.;
RT   "Oryza sativa chromosome 3 BAC OSJNBa0004G17 genomic sequence.";
RL   Submitted (AUG-2002) to the EMBL/GenBank/DDBJ databases.
CC   -!- SIMILARITY: CONTAINS 1 SET DOMAIN.
DR   EMBL; AC091775; AAM97151.1; -.
DR   Gramene; Q8LN53; -.
DR   GO; GO:0005489; F:electron transporter activity; IEA.
DR   GO; GO:0006118; P:electron transport; IEA.
DR   InterPro; IPR003149; Fe_hyd_SSU.
DR   InterPro; IPR001214; SET.
DR   InterPro; IPR002893; Znf_MYND.
DR   Pfam; PF02256; Fe_hyd_SSU; 1.
DR   Pfam; PF00856; SET; 1.
DR   Pfam; PF01753; zf-MYND; 1.
DR   SMART; SM00317; SET; 1.
DR   PROSITE; PS50280; SET; 1.
DR   PROSITE; PS01360; ZF_MYND_1; UNKNOWN_1.
DR   PROSITE; PS50865; ZF_MYND_2; 1.
KW   Hypothetical protein.
FT   NON_TER     425    425       
SQ   SEQUENCE   425 AA;  48052 MW;  5823CFFD8308AEA3 CRC64;
     MASWEEQLRD ELAGRDLAVA SVPGKGRGLF AARSFFPGEV VISQEPYAST PNKISVGSNC
     DNCFASRNLR KCSVCRVAWY CGSACQREEW KLHQLECRAI AALTEDRKKM LTPTIRLMVR
     LVLRRKLQDD KAIPSSGTDN YNLVDALESH ISEVDKNQLV LYAQMANLVQ LILPSFELDL
     KEITHTFSKF ACNAHTICDP ELRPLGTGLY PVLSIINHSC VPNAVLIFEG RTAYVRALQP
     ISKNEEVSIS YIETAATTMK RQDDLKHYYF TCTCPRCVKD SEEDALLEGY RCNDQKCDGF
     LLPNAGNKGY TCQKCSTSRD GEELQKMASD VLLLSDKVSS LVSSGNNSEV GSMYKTIEEL
     ERKLYHPLSI TLLHTRETLL KIYMELQDWQ TALMYCRLTI PVYERIYPPF HPMIGLQFYT
     CGKLE
//
>Q8RUS3
ID   Q8RUS3      PRELIMINARY;      PRT;   736 AA.
AC   Q8RUS3;
DT   01-JUN-2002 (TrEMBLrel. 21, Created)
DT   01-JUN-2002 (TrEMBLrel. 21, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   Similar to SET1.
GN   P0425G02.10 OR P0468B07.30.
OS   Oryza sativa (japonica cultivar-group).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=39947;
RN   [1]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Sasaki T., Matsumoto T., Yamamoto K.;
RT   "Oryza sativa nipponbare(GA3) genomic DNA, chromosome 1, PAC
RT   clone:P0425G02.";
RL   Submitted (FEB-2001) to the EMBL/GenBank/DDBJ databases.
RN   [2]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Sasaki T., Matsumoto T., Yamamoto K.;
RT   "Oryza sativa nipponbare(GA3) genomic DNA, chromosome 1, PAC
RT   clone:P0468B07.";
RL   Submitted (FEB-2001) to the EMBL/GenBank/DDBJ databases.
CC   -!- SIMILARITY: CONTAINS 1 SET DOMAIN.
DR   EMBL; AP003247; BAB85235.1; -.
DR   EMBL; AP003260; BAB89651.1; -.
DR   Gramene; Q8RUS3; -.
DR   InterPro; IPR003105; G9a.
DR   InterPro; IPR003616; PostSET.
DR   InterPro; IPR007728; Pre-SET.
DR   InterPro; IPR001214; SET.
DR   Pfam; PF05033; Pre-SET; 1.
DR   Pfam; PF00856; SET; 1.
DR   Pfam; PF02182; YDG_SRA; 1.
DR   SMART; SM00508; PostSET; 1.
DR   SMART; SM00317; SET; 1.
DR   SMART; SM00466; SRA; 1.
DR   PROSITE; PS50868; POST_SET; 1.
DR   PROSITE; PS50867; PRE_SET; 1.
DR   PROSITE; PS50280; SET; 1.
SQ   SEQUENCE   736 AA;  80094 MW;  8B65DC9173F83E57 CRC64;
     MNRESNFMPT PDQDVLEVKP LRTLAPMFPA PLGIDVLNRL TAPPLVFVAP AGQFPGGFGS
     LNIPAVRSFA AFGGQDASGG KTAGGGDQDA SGGKTAAGGD QDAGRGETAA FGGQETVRGE
     FVANGTPNVG ASATGPIDAT PISACKSTQP SVISLDDDDN DDDEPYGGNQ TSASGRKIKR
     PSHLKGYNVS DGLGTDSSNG TKKRPKTSNR KAATDNEISL MPPSSDPREV VEVLLMTFEA
     LRRRHLQLDE TQETSKRADL KAGAIMLASN LRANIGKRIG AVPGVEVGDI FYFRMELCII
     GLHAPSMGGI DYMNKFGDED DSVAICIVAA GVYENDDDDT DTLVYSGSGG ISRNSEEKQD
     QKLERGNLAL ERSLSRKNVI RVVRGYKDPA CLTGKVYIYD GLYKIHESWK ERTKTGINCF
     KYKLQREPGQ PDAVAIWKMC QRWVENPAAR GKVLHPDLSS GAENLPVCLI NDVNSEKGPG
     HFNYITQVKY LKPLRSMKPF QGCRCTSVCL PGDTSCDCAQ HNGGDLPYSS SGLLVCRKLM
     VYECGESCRC SINCRNRVAQ KGVRIHLEVF RTTNRGWGLR SWDPIRAGSF ICEYVGEVVD
     DTKVNLDGED DYLFRTVCPG EKTLKWNYGP ELIGEHSINI SADTFEPLPI KISAMKMGNV
     ARFMNHSCNP NTFWQPVQFD HGEDGYPHIM FFALKHIPPM TELTYDYGDI GCESRGVGSR
     AKNCLCGSSN CRGFFS
//
>Q8S1J4
ID   Q8S1J4      PRELIMINARY;      PRT;   374 AA.
AC   Q8S1J4;
DT   01-JUN-2002 (TrEMBLrel. 21, Created)
DT   01-JUN-2002 (TrEMBLrel. 21, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   P0695H10.8 protein.
GN   P0695H10.8.
OS   Oryza sativa (japonica cultivar-group).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=39947;
RN   [1]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Sasaki T., Matsumoto T., Yamamoto K.;
RT   "Oryza sativa nipponbare(GA3) genomic DNA, chromosome 1, PAC
RT   clone:P0695H10.";
RL   Submitted (FEB-2001) to the EMBL/GenBank/DDBJ databases.
CC   -!- SIMILARITY: CONTAINS 1 SET DOMAIN.
DR   EMBL; AP003295; BAB89848.1; -.
DR   Gramene; Q8S1J4; -.
DR   InterPro; IPR004883; DUF260.
DR   InterPro; IPR007728; Pre-SET.
DR   InterPro; IPR001214; SET.
DR   Pfam; PF03195; DUF260; 1.
DR   Pfam; PF05033; Pre-SET; 1.
DR   Pfam; PF00856; SET; 1.
DR   SMART; SM00317; SET; 1.
DR   PROSITE; PS50891; LOB; 1.
DR   PROSITE; PS50280; SET; 1.
SQ   SEQUENCE   374 AA;  41599 MW;  6EEE52153AFC960C CRC64;
     MGSLRECGDG CACGPSCGNR RTQLGVTVRL RVVRHREKGW GLHAAEVLRR GQFVCEYAGE
     LLTTEEARRR QGLYDELASV EISSKEKSSP SVMVMLDLGR MACRAFAESG GDEDESFDKE
     DSWREWRTQQ KNNLVPLQSF IQSTLPFPLS LAFVSSVQQP QLMPMPPLPM PHVPFALALQ
     VLSEVFGASN VAKLLSRVPA ALRREAARTV CYEAQARIAD PVYGSVGTIL ALQHQNKFMS
     QTQTDTNNID PYEKFRSSDS KLHYARRQVS LLQGQLSVLE SQLFNLRVAL ASAHPDTPPQ
     HFVVLQPAHS AASTLNQVVV NYDDLPHAVD FMDAEPAALR GLESLQLSQP LQREEDEGHR
     DMNLFSDSVG QRQL
//
>Q8S1X3
ID   Q8S1X3      PRELIMINARY;      PRT;   676 AA.
AC   Q8S1X3;
DT   01-JUN-2002 (TrEMBLrel. 21, Created)
DT   01-JUN-2002 (TrEMBLrel. 21, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   Putative SUVH4.
GN   P0482D04.21 OR OSJNBA0093F16.17.
OS   Oryza sativa (japonica cultivar-group).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=39947;
RN   [1]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Sasaki T., Matsumoto T., Yamamoto K.;
RT   "Oryza sativa nipponbare(GA3) genomic DNA, chromosome 1, PAC
RT   clone:P0482D04.";
RL   Submitted (FEB-2001) to the EMBL/GenBank/DDBJ databases.
RN   [2]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Sasaki T., Matsumoto T., Yamamoto K.;
RT   "Oryza sativa nipponbare(GA3) genomic DNA, chromosome 1, BAC
RT   clone:OSJNBa0093F16.";
RL   Submitted (NOV-2001) to the EMBL/GenBank/DDBJ databases.
DR   EMBL; AP003262; BAB89674.1; -.
DR   EMBL; AP004332; BAB92897.1; -.
DR   Gramene; Q8S1X3; -.
DR   InterPro; IPR003105; G9a.
DR   InterPro; IPR003616; PostSET.
DR   InterPro; IPR007728; Pre-SET.
DR   InterPro; IPR001214; SET.
DR   Pfam; PF05033; Pre-SET; 1.
DR   Pfam; PF00856; SET; 1.
DR   Pfam; PF02182; YDG_SRA; 1.
DR   PROSITE; PS50868; POST_SET; 1.
DR   PROSITE; PS50867; PRE_SET; 1.
DR   PROSITE; PS50280; SET; 1.
SQ   SEQUENCE   676 AA;  74816 MW;  92677BDC449DCF68 CRC64;
     MEVMDSVAVM EVSPVPKPPL EAALALRRSV RCLNRTRRPT YVEQEEPKES AGRRRGGKRK
     REEEKKEPVA QHAMKPVRMG DAASERKPSS EGKPMPAIAA EPVSCAGFAR PAAEDDVLGN
     GKSAKLRVKE TLRAFTSHYL HLVQERMLSD NALVEFQEEQ KRAQAVLQEG QKRPSKRPDL
     KAITKMQESN AVLYPEKIIG ELPGVDVGDQ FYSRAEMVVL GIHSHWLNGI DYMGMKYQGK
     EEYANLTFPL ATCIVMSGIY EDDLDKADEI IYTGQGGNDL LGNHRQIGSQ QLQRGNLALK
     NSKDNGNPIR VIRGHISKNS YTGKVYTYDG LYKVVDDWVQ NGVQGHVVFK YKLKRLEGQP
     SLTTSEVRFT RAEAPTTISE LPGLVCDDIS GGQENLPIPA TNLVDDPPVP PTGFVYSKSL
     KIPKGIKIPS YCNGCDCEGD CANNKNCSCA QRNGSDLPYV SHKNIGRLVE PKAIVFECGA
     NCSCNNNCVN RTSQKGLQYR LEVFKTASKG WGVRTWDTIL PGAPICEYTG VLRRTEEVDG
     LLQNNYIFDI DCLQTMKGLD GREKRAGSDM HLPSLHAEND SDPPAPEYCI DAGSIGNFAR
     FINHSCEPNL FVQCVLSSHN DVKLAKVTLF AADTILPLQE LSYDYGYVLD SVVGPDGNIV
     KLPCFCGAPY CRKRLY
//
>Q8S3S4
ID   Q8S3S4      PRELIMINARY;      PRT;   761 AA.
AC   Q8S3S4;
DT   01-JUN-2002 (TrEMBLrel. 21, Created)
DT   01-JUN-2002 (TrEMBLrel. 21, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   Putative SET-domain transcriptional regulator.
GN   49D11.8.
OS   Oryza sativa (japonica cultivar-group).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=39947;
RN   [1]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Park Y.-J., Rostoks N., Ramakrishna W., SanMiguel P., Shiloff B.,
RA   Ma J., Jiang Z., Kleinhofs A., Bennetzen J.;
RT   "Sequence characterization of orthologous regions in the barley and
RT   rice genomes.";
RL   Submitted (FEB-2002) to the EMBL/GenBank/DDBJ databases.
CC   -!- SIMILARITY: CONTAINS 1 SET DOMAIN.
DR   EMBL; AF480496; AAL87154.1; -.
DR   Gramene; Q8S3S4; -.
DR   GO; GO:0016020; C:membrane; IEA.
DR   GO; GO:0045285; C:ubiquinol-cytochrome c reductase complex; IEA.
DR   GO; GO:0008121; F:ubiquinol-cytochrome c reductase activity; IEA.
DR   GO; GO:0006118; P:electron transport; IEA.
DR   InterPro; IPR003616; PostSET.
DR   InterPro; IPR007728; Pre-SET.
DR   InterPro; IPR005805; Rieske.
DR   InterPro; IPR001214; SET.
DR   InterPro; IPR007087; Znf_C2H2.
DR   Pfam; PF05033; Pre-SET; 1.
DR   Pfam; PF00856; SET; 1.
DR   Pfam; PF00096; zf-C2H2; 3.
DR   SMART; SM00508; PostSET; 1.
DR   SMART; SM00317; SET; 1.
DR   SMART; SM00355; ZnF_C2H2; 4.
DR   PROSITE; PS50868; POST_SET; 1.
DR   PROSITE; PS50867; PRE_SET; 1.
DR   PROSITE; PS00200; RIESKE_2; 1.
DR   PROSITE; PS50280; SET; 1.
DR   PROSITE; PS00028; ZINC_FINGER_C2H2_1; 4.
DR   PROSITE; PS50157; ZINC_FINGER_C2H2_2; 3.
KW   Metal-binding; Zinc; Zinc-finger.
SQ   SEQUENCE   761 AA;  86129 MW;  C18D9A3C286DED14 CRC64;
     MPQILAEVSK NPDVGEFLLK LISSEREKLS HVWGFGTDSS NQMHSENQDG SVMVLREDGT
     HPSPGLKCKI CSQEFSDDQG LGLHWTEVHK KEVRWLFRGY SCAVCMDSFT NRRVLERHVQ
     EKHGAQYLQY STLLRCISCN SNFLNTDLLW QHIVSDHSRD FSLLDHVPRR PRGQSIKRTE
     RASDELLYDN HNLGKDDGLQ KFTCRLCGMM FDLLPDLGHH HQVAHTNSGT VSDIPSGREK
     YQFNRGRHYY SAFKKSLRPS GSLKKRTSSG VEKHFKAQSL DLSMDTSHIV ESETTTLGRL
     LDFQCSDVAL TLFSKIQKTR PHPSNLDILS IARSVCCKTS LRAALKAKYG ILPDNIFVKA
     AKLCSDVGIQ IDWHQEEFFC PKGCKSRSSS NSLLPLQPTQ VDFVMSPPIG DEIWGMDEYH
     YVLDSEHFGW NLKNEMVIVC EDVSFGREKV PVVCAIDVDA KEFPYMKPGE ILQSENSLPW
     QGFHYVTKRL MDSSLVDSEN TMVGCACSHA HCSPEECDHV SLFDSIYENL VDLHGVPMRG
     RFAYDENSKV ILQEGYPIYE CNSSCTCDAS CQNKVLQRGL LVKLEVFRTE NKGWAVRAAE
     PIPQGTFVCE YIGEVLKMKD DGAIRHVERL EIYWNFSGAF HKLIRKLLDL REAKSGSSYL
     FEITSQIDRE RVQTTGTTAY VIDATRYGNV SRFINHSCSP NLSTRLVSVE SKDCQLAHIG
     LFANQDILMG EELAYDYGQK LLPGDGCPCH CGAKNCRGRV Y
//
>Q8S7V1
ID   Q8S7V1      PRELIMINARY;      PRT;   536 AA.
AC   Q8S7V1;
DT   01-JUN-2002 (TrEMBLrel. 21, Created)
DT   01-JUN-2002 (TrEMBLrel. 21, Last sequence update)
DT   01-MAR-2003 (TrEMBLrel. 23, Last annotation update)
DE   Hypothetical 57.7 kDa protein.
GN   OSJNBA0091P11.26.
OS   Oryza sativa (japonica cultivar-group).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=39947;
RN   [1]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Buell C.R., Yuan Q., Ouyang S., Liu J., Moffat K.S., Hill J.N.,
RA   Gansberger K., Brenner M., Burgess S., Hance M., Shvartsbeyn M.,
RA   Tsitrin T., Riggs F., Hsiao J., Zismann V., Blunt S., Pai G.,
RA   VanAken S.E., Utterback T.R., Feldblyum T.V., Kalb E., Quackenbush J.,
RA   Salzberg S.L., White O., Fraser C.M.;
RT   "Oryza sativa chromosome 3 BAC OSJNBa0091P11 genomic sequence.";
RL   Submitted (APR-2002) to the EMBL/GenBank/DDBJ databases.
CC   -!- SIMILARITY: CONTAINS 1 SET DOMAIN.
DR   EMBL; AC073556; AAL84316.1; -.
DR   Gramene; Q8S7V1; -.
DR   InterPro; IPR001214; SET.
DR   InterPro; IPR001440; TPR.
DR   Pfam; PF00856; SET; 1.
DR   Pfam; PF00515; TPR; 2.
DR   SMART; SM00317; SET; 1.
DR   PROSITE; PS50280; SET; 1.
KW   Hypothetical protein.
SQ   SEQUENCE   536 AA;  57699 MW;  C096D07982F8D8DB CRC64;
     MATPGLDDDS LQQLRSRATQ LLLKENWTEY IAVCSLIIEA FDAAAACKDR RVLCSTLAHR
     ADARARLGDA PGALADCDAA LAADPAHPGA LLSKGAVLRG LGRYSRAAEC FRAALAVSGT
     DEVREMVEQC KRLDAQARSG AVDLSEWVLA GFSGKCPDLA EHVGAVEVRR SAHGGRGVFA
     VKNIEAGANL VISKAVAIGR GVIPDAADSG EKMVVWKDLV DKVLDAAEKC PRTASLIYTL
     STGEEPEDEL PIPDMAHFKQ ETEELDDGTA MAPKASLDVD KILKVLDVNC LTEDAAPSAN
     LLGSNGVVNC GVGLWILPAF INHSCHPNAR RTHVGDHAIV HASRDIKAGE EITFAYFDVL
     TPASKRREAA RAWGLECQCD RCRFEASDAI VGQELTKLEN ELVNGRGGDM GALVVRLEER
     MRKSMVKERR KAFLRASFWS AYSALFDSDK LVRKWGRRVP GEAAVAESVA GAIGGNESVL
     RAMLRGADNG NGCGNRLEVE DKVVRIGRAT YGRVVKRQAM RALFRLTLDA DSNKSL
//
>Q9AT64
ID   Q9AT64      PRELIMINARY;      PRT;   812 AA.
AC   Q9AT64;
DT   01-JUN-2001 (TrEMBLrel. 17, Created)
DT   01-JUN-2001 (TrEMBLrel. 17, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   SET1.
GN   SET1.
OS   Oryza sativa (Rice).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=4530;
RN   [1]
RP   SEQUENCE FROM N.A.
RA   Krauss V., Fischer A., Naumann K., Hofmann I., Tschiersch B.,
RA   Schulz I., Fransz P., Schotta G., Dorn R., Reuter G.;
RT   "Heterochromatin-associated proteins and gene silencing in
RT   Arabidopsis.";
RL   Submitted (FEB-2001) to the EMBL/GenBank/DDBJ databases.
CC   -!- SIMILARITY: CONTAINS 1 SET DOMAIN.
DR   EMBL; AF344453; AAK28975.1; -.
DR   Gramene; Q9AT64; -.
DR   GO; GO:0005634; C:nucleus; IEA.
DR   GO; GO:0003677; F:DNA binding activity; IEA.
DR   GO; GO:0006355; P:regulation of transcription, DNA-dependent; IEA.
DR   InterPro; IPR000637; AT_hook.
DR   InterPro; IPR003105; G9a.
DR   InterPro; IPR003616; PostSET.
DR   InterPro; IPR007728; Pre-SET.
DR   InterPro; IPR001214; SET.
DR   Pfam; PF02178; AT_hook; 5.
DR   Pfam; PF05033; Pre-SET; 1.
DR   Pfam; PF00856; SET; 1.
DR   Pfam; PF02182; YDG_SRA; 1.
DR   PRINTS; PR00929; ATHOOK.
DR   SMART; SM00384; AT_hook; 5.
DR   SMART; SM00317; SET; 1.
DR   SMART; SM00466; SRA; 1.
DR   PROSITE; PS50868; POST_SET; 1.
DR   PROSITE; PS50867; PRE_SET; 1.
DR   PROSITE; PS50280; SET; 1.
SQ   SEQUENCE   812 AA;  89127 MW;  ABD786451279811B CRC64;
     MAGTRQTTSV PMDNAAVVDA KPLRTLTPMF PAALGLHTFT AKENSSSIVC ITPFGPYAGG
     TEQAMPASIP PMFASPAAPA DPNQRQPYAV HLNGAAPANG TANNTGVIPD LQIAVAGTVE
     SAKRKRGRPK RVQDSSVPSA HLVPSAPGGN ITAVQTPPSA TTDESGKKKR GRPKRVQDVP
     VLSTPSAPQV DSTVFQTPAS AVNESVTRKR GRPRRVQDGA DTSAPPIQSK YNEPVLQTPS
     AVTLPEDGKR KRGRPKRVPD GALIPLSHSG VSIDDDSGEI ITGKRGRPRK IDVNLLNLPS
     LFSDDPRESV DNVLMMFDAL RRRLMQLDEV KQGAKQQHNL KAGSIMMSAE LRANKNKRIG
     EVPGVEVGDM FYFRIEMCLV GLNSQSMSGI DYMSAKFGNE EDPVAISIVS AGVYENTEDD
     PDVLVYTGQG MSGKDDQKLE RGNLALERSL HRGNQIRVVR SVRDLTCPTG KIYIYDGLYK
     IREAWVEKGK TGFNVFKHKL LREPGQPDGI AVWKKTEKWR ENPSSRDHVI LRDISYGAES
     KPVCLVNEVD DEKGPSHFNY TTKLNYRNSL SSMRKMQGCN CASVCLPGDN NCSCTHRNAG
     DLPYSASGIL VSRMPMLYEC NDSCTCSHNC RNRVVQKGSQ IHFEVFKTGD RGWGLRSWDP
     IRAGTFICEY AGEVIDRNSI IGEDDYIFET PSEQNLRWNY APELLGEPSL SDSSETPKQL
     PIIISAKRTG NIARFMNHSC SPNVFWQPVL YDHGDEGYPH IAFFAIKHIP PMTELTYDYG
     QSQGNVQLGI NSGCRKSKNC LCWSRKCRGS FG
//
>Q9FP07
ID   Q9FP07      PRELIMINARY;      PRT;   717 AA.
AC   Q9FP07;
DT   01-MAR-2001 (TrEMBLrel. 16, Created)
DT   01-MAR-2001 (TrEMBLrel. 16, Last sequence update)
DT   01-JUN-2003 (TrEMBLrel. 24, Last annotation update)
DE   Putative curly leaf protein.
GN   P0038C05.17.
OS   Oryza sativa (Rice).
OC   Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta;
OC   Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae;
OC   Ehrhartoideae; Oryzeae; Oryza.
OX   NCBI_TaxID=4530;
RN   [1]
RP   SEQUENCE FROM N.A.
RC   STRAIN=cv. Nipponbare;
RA   Sasaki T., Matsumoto T., Yamamoto K.;
RT   "Oryza sativa nipponbare(GA3) genomic DNA, chromosome 6, PAC
RT   clone:P0038C05.";
RL   Submitted (DEC-2000) to the EMBL/GenBank/DDBJ databases.
CC   -!- SIMILARITY: CONTAINS 1 SET DOMAIN.
DR   EMBL; AP003044; BAB19344.1; -.
DR   Gramene; Q9FP07; -.
DR   GO; GO:0005634; C:nucleus; IEA.
DR   GO; GO:0003677; F:DNA binding activity; IEA.
DR   InterPro; IPR001005; Myb_DNA_binding.
DR   InterPro; IPR001214; SET.
DR   Pfam; PF00856; SET; 1.
DR   SMART; SM00717; SANT; 1.
DR   SMART; SM00317; SET; 1.
DR   PROSITE; PS50280; SET; 1.
SQ   SEQUENCE   717 AA;  80662 MW;  B3D5F3ED059D56A4 CRC64;
     MVTVTIQHTF SLERNQRMQE DQSVLGRRRI YYDTNCGEAL ICSDSEDEAV EDEEEKKEFK
     DSEDCIIRMT IQECGMSDAV LETLARDIER APDDIKARYE ILQGEKPEGS SKKVSELNVK
     MEDVYGDKDL DAALDSFDNL FCRRCLVFDC KLHGCSQDLV FPTEKQAPLC SSDEGTPCGI
     HCYKLVSKPD AIMEIDSHLL VDVEEPTSDN LKDQIGSNKK KLGSSGQKTK SQQSESSSTA
     RVSSESSESE GQQEMSPDSN SIVNGCHWPR DMKLRSDTRS GIKDSVVSSQ CNSPSTRSFR
     KKGTLQMENN SSFVDAQSDS MEDTNNEHSA TDGCDSSRKE ECVDESICRQ EAHGRSWKVI
     EQGLLLKGLE IFGKNSCLIA RNLLGGMKTC TDVFQYMNYI ENSSASGALS GVDSLVKGYM
     KGNELRTRSR FVRRRGRVRR LKYTWKTAGY HFIRKRITER KDQPCRQYTP CGCQSACGKQ
     CPCLTNGTCC EKYCGCPKMC KNRFRGCHCA KSQCRSRQCP CFAADRECDP DVCRNCWVGC
     GDGTLGVPNQ RGDNYECRNM KLLLKQQQRV LLGRSDVSGW GAFLKNSVGK HEYLGEYTGE
     LISHKEADKR GKIYDRENSS FLFNLNNEYV LDAYRMGDKL KFANHSPDPN CYAKVIMVAG
     DHRVGIFAKE RISAGEELFY DYRYEPDRAP AWARKPEGPG AKDDAQPSTG RAKKLAH
//
