import logging

from helloworld.lib.base import *

log = logging.getLogger(__name__)
import StringIO
from pymodule import PassingData, getListOutOfStr

class DisplaytopsnptestrmController(BaseController):
	"""
	2008-10-26
		controller in charge of displaying results from CandidateGeneTopSNPTestRM
	"""
	def index(self):
		# Return a rendered template
		#   return render('/some/template.mako')
		# or, Return a response
		CandidateGeneTopSNPTestRMType = model.Stock_250kDB.CandidateGeneTopSNPTestRMType

		rows = CandidateGeneTopSNPTestRMType.query.order_by(CandidateGeneTopSNPTestRMType.results_type).\
			order_by(CandidateGeneTopSNPTestRMType.test_type_id).\
			order_by(CandidateGeneTopSNPTestRMType.null_distribution_type_id).\
			order_by(CandidateGeneTopSNPTestRMType.get_closest).\
			order_by(CandidateGeneTopSNPTestRMType.min_MAF).\
			order_by(CandidateGeneTopSNPTestRMType.allow_two_sample_overlapping).all()
		"""
		rows = model.db.metadata.bind.execute("select y.get_closest, y.min_MAF, y.allow_two_sample_overlapping, \
			y.results_type, y.test_type_id, y.null_distribution_type_id, group_concat(y.id order by y.id) as type_id_ls from %s y \
			group by y.get_closest, y.min_MAF, y.allow_two_sample_overlapping, \
			y.results_type, y.test_type_id, y.null_distribution_type_id"%CandidateGeneTopSNPTestRMType.table.name)
		"""
		c.rows = rows
		"""
		for row in rows:
			row.null_distribution_type = model.Stock_250kDB.NullDistributionType.get(row.null_distribution_type_id)
			row.test_type = model.Stock_250kDB.AnalysisMethod.get(row.test_type_id)
			c.rows.append(row)
		"""
		return render('/display_top_snp_test_rm.html')
	
	
	def type(cls, id=None, TypeClass=model.Stock_250kDB.CandidateGeneTopSNPTestRMType, \
			template='/display_top_snp_test_rm_type.html', phenotype_id_ls_str = '1-7,39-61,80-82', \
			list_type_id_ls_str = '1-3,6,8,28,51,64,65,68,71,76,129'):
		"""
		2008-10-30
			generalized so that DisplayResultsGene could call it
		"""
		ResultsMethod = model.Stock_250kDB.ResultsMethod
		
		if id is None:
			id = request.params.get('id', '1')
		
		phenotype_id_ls = getListOutOfStr(phenotype_id_ls_str, data_type=str)
		list_type_id_ls = getListOutOfStr(list_type_id_ls_str, data_type=str)
		
		#extra_tables = ' %s c '%(CandidateGeneTopSNPTestRM.table.name)
		extra_condition = 'p.id in (%s)'%(','.join(phenotype_id_ls))
		
		c.phenotype_info  = h.getPhenotypeInfo(extra_condition=extra_condition, extra_tables=None)
		#extra_condition = 's.type_id =%s'%id
		extra_condition = 'p.id in (%s)'%(','.join(list_type_id_ls))
		
		c.list_info = h.getListTypeInfo(extra_condition=extra_condition)
		
		data_matrix = []
		no_of_rows = len(c.list_info.list_type_id_ls)
		no_of_cols = len(c.phenotype_info.phenotype_method_id_ls)
		for i in range(no_of_rows):
			data_matrix.append([None]*no_of_cols)
		
		c.type = TypeClass.get(id)
		
		#2008-10-29 a faster way to come up the data_matrix but data is not guaranteed inside
		rows = ResultsMethod.query.filter(ResultsMethod.phenotype_method_id.in_(map(int, phenotype_id_ls))).\
			filter(ResultsMethod.analysis_method_id.in_([1,7])).\
			filter_by(call_method_id=17).\
			order_by(ResultsMethod.analysis_method_id)
		counter = 0
		for row in rows:
			col_index = c.phenotype_info.phenotype_method_id2index.get(row.phenotype_method_id)
			if col_index is None:
				continue
			for list_type_id, row_index in c.list_info.list_type_id2index.iteritems():
				if list_type_id>0:
					if data_matrix[row_index][col_index] is None:
						data_matrix[row_index][col_index] = []
					data_matrix[row_index][col_index].append((row.id, row.analysis_method.short_name))
					counter +=1
		"""
		rows = CandidateGeneTopSNPTestRM.query.filter_by(type_id=id)
		
		for row in rows:
			row_index = c.list_info.list_type_id2index[row.list_type_id]
			col_index = c.phenotype_info.phenotype_method_id2index[row.result.phenotype_method_id]
			if data_matrix[row_index][col_index] is None:
				data_matrix[row_index][col_index] = Set()
			data_matrix[row_index][col_index].add(row.results_id)
			counter +=1
		"""
		c.counter = counter
		c.data_matrix = data_matrix
		return render(template, cache_expire=5)
	
	type=classmethod(type)
	
	def getImage(self, id=None):
		"""
		2008-10-26
			get image from a file(path=id), which is generated by showOne()
		"""
		response.headers['Content-type'] = 'image/png'
		plot_file_path = os.path.join(config['app_conf']['plots_store'], id)
		img_data = None
		if os.path.isfile(plot_file_path):
			inf = open(plot_file_path, 'rb')
			img_data = inf.read()
			del inf
		if not img_data:
			response.headers['Content-type'] = 'text/plain'
			img_data = 'No Image'
		return img_data
		
	def showOne(self, id=None, type_id=None, list_type_id=None):
		"""
		2008-10-30
			add code to DrawTopSNPTest2DMapForOneRM.plotCurve()
		2008-10-24
			show all data identified by (results_id=id, type_id=type_id, list_type_id=list_type_id)
		"""
		type_id = request.params.get('type_id', type_id)
		list_type_id = request.params.get('list_type_id', list_type_id)
		results_id = request.params.get('id', id)
		if results_id is None:
			results_id = request.params.get('results_id', None)
		if results_id is None:
			return 'Nothing'
		
		from_where_clause = "from %s t, %s y where t.type_id=y.id and t.results_id=%s and t.list_type_id=%s and y.id =%s"%\
			(model.Stock_250kDB.CandidateGeneTopSNPTestRM.table.name, model.Stock_250kDB.CandidateGeneTopSNPTestRMType.table.name,\
			results_id, list_type_id, type_id)
		
		from variation.src.DrawTopSNPTest2DMapForOneRM import DrawTopSNPTest2DMapForOneRM
		no_of_top_snps_info = DrawTopSNPTest2DMapForOneRM.get_no_of_top_snps_info(model.db, from_where_clause)
		min_distance_info = DrawTopSNPTest2DMapForOneRM.get_min_distance_info(model.db, from_where_clause)
		rdata = DrawTopSNPTest2DMapForOneRM.get_data_matrix(model.db, no_of_top_snps_info, min_distance_info, from_where_clause, need_other_values=True)
		
		c.result = model.Stock_250kDB.ResultsMethod.get(results_id)
		c.list_type = model.Stock_250kDB.GeneListType.get(list_type_id)
		c.no_of_top_snps_info = no_of_top_snps_info
		c.min_distance_info = min_distance_info
		c.rdata = rdata
		#c.rdata.data_matrix_non_candidate_gw_size = 250000-c.rdata.data_matrix_candidate_gw_size
		from pymodule.DrawMatrix import drawMatrixLegend
		
		
		
		#draw the pvalue plot
		curve_fname = 'top_snp_test_%s_%s_%s_curve.png'%(results_id, list_type_id, type_id)
		plot_fname = 'top_snp_test_%s_%s_%s_pvalue.png'%(results_id, list_type_id, type_id)
		plot_file_path = os.path.join(config['app_conf']['plots_store'], plot_fname)
		curve_file_path = str(os.path.join(config['app_conf']['plots_store'], curve_fname))	#str() to avoid "TypeError: cannot return std::string from Unicode object"
		c.pvalue_png_fname = plot_fname
		if len(c.rdata.data_matrix)>1 and len(c.rdata.data_matrix[0])>1:
			im = drawMatrixLegend(c.rdata.data_matrix, left_label_ls=no_of_top_snps_info.label_ls, \
							top_label_ls=min_distance_info.label_ls, min_value=c.rdata.min_value, max_value=c.rdata.max_value)
			png_data = StringIO.StringIO()
			im.save(plot_file_path, format='png')
			DrawTopSNPTest2DMapForOneRM.plotCurve(rdata, no_of_top_snps_info, min_distance_info, curve_file_path)
		c.curve_fname = curve_fname
		
		#	self.savePlot(c.snp_region_plot, plot_file_path)
		"""
		im = drawMatrixLegend(c.rdata.data_matrix_candidate_sample_size/c.rdata.data_matrix_candidate_gw_size, \
							left_label_ls=no_of_top_snps_info.label_ls, \
							top_label_ls=min_distance_info.label_ls)
		"""
		plot_fname = 'top_snp_test_%s_%s_%s_candidate_sample.png'%(results_id, list_type_id, type_id)
		plot_file_path = os.path.join(config['app_conf']['plots_store'], plot_fname)
		#im.save(plot_file_path, format='png')
		c.candidate_sample_png_fname = plot_fname
		
		"""
		im = drawMatrixLegend(c.rdata.data_matrix_non_candidate_sample_size, left_label_ls=no_of_top_snps_info.label_ls, \
							top_label_ls=min_distance_info.label_ls)
		"""
		plot_fname = 'top_snp_test_%s_%s_%s_non_candidate_sample.png'%(results_id, list_type_id, type_id)
		plot_file_path = os.path.join(config['app_conf']['plots_store'], plot_fname)
		#im.save(plot_file_path, format='png')
		c.non_candidate_sample_png_fname = plot_fname
		
		return render('/display_top_snp_test_rm_one.html')