#!/bin/sh
APPDIR=`dirname $0`;
/usr/lib/jvm/ia32-java-6-sun-1.6.0.07/bin/java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:$APPDIR/../../gwt-user.jar:$APPDIR/../../gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" com.google.gwt.sample.mail.Mail;
