#!/bin/sh
APPDIR=`dirname $0`;
HOMEDIR=~;
/usr/lib/jvm/ia32-java-6-sun/bin/java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:$HOMEDIR/script/gwt/gwt-user.jar:$HOMEDIR/script/gwt/gwt-dev-linux.jar:$HOMEDIR/script/gwt-visualization/gwt-visualization.jar:$HOMEDIR/script/gwt-maps/gwt-maps.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" edu.nordborglab.Accession;

# 2009-4-15 link the directory into Accession/ because haploGroup is an action of controller Accession in pylons.
#cd $APPDIR/www/edu.nordborglab.Accession;
#ln -s ../edu.nordborglab.HaploGroup ./haploGroup;
