#!/bin/sh
APPDIR=`dirname $0`;
HOMEDIR=~;
/usr/lib/jvm/ia32-java-6-sun/bin/java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:$HOMEDIR/script/gwt-linux-1.5.3/gwt-user.jar:$HOMEDIR/script/gwt-linux-1.5.3/gwt-dev-linux.jar:$HOMEDIR/script/gwt-visualization-1.0.0/gwt-visualization.jar:$HOMEDIR/script/gwt-maps-1.0.2/gwt-maps.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" edu.nordborglab.Accession;
