#!/bin/sh
APPDIR=`dirname $0`;
HOMEDIR=~;
/usr/lib/jvm/ia32-java-6-sun/bin/java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/usr/local/home_ubuntu/crocea/script/gwt-linux-1.5.3/gwt-user.jar:/usr/local/home_ubuntu/crocea/script/gwt-linux-1.5.3/gwt-dev-linux.jar:/usr/local/home_ubuntu/crocea/script/gwt-visualization-1.0.0/gwt-visualization.jar:$HOMEDIR/script/gwt-maps-1.0.2/gwt-maps.jar:$HOMEDIR/script/gwt-linux-1.5.3/tuple.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" edu.nordborglab.Accession/Accession.html;
