#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/usr/local/home_ubuntu/crocea/script/gwt-linux-1.5.3/gwt-user.jar:/usr/local/home_ubuntu/crocea/script/gwt-linux-1.5.3/gwt-dev-linux.jar:/home/crocea/script/gwt-maps-1.0.2/gwt-maps.jar:/home/crocea/script/gwt-visualization-1.0.0/gwt-visualization.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" edu.nordborglab.GWASOnePhenotype;

# 2009-4-23 link the directory into GWASPhenotypes because getGWA is an action of controller DisplayResults in pylons.
#cd $APPDIR/www/edu.nordborglab.GWASPhenotypes;
#ln -s ../edu.nordborglab.GWASOnePhenotype ./showGWA;
