#!/bin/sh
APPDIR=`dirname $0`;
HOMEDIR=~;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:$HOMEDIR/script/gwt/gwt-user.jar:$HOMEDIR/script/gwt/gwt-dev-linux.jar:$HOMEDIR/script/gwt-visualization/gwt-visualization.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" edu.nordborglab.HaplotypeView;
