#!/bin/sh
APPDIR=`dirname $0`;
CLASSNAME=edu.nordborglab.HaploGroup;
/usr/lib/jvm/ia32-java-6-sun/bin/java -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/usr/local/home_ubuntu/crocea/script/gwt-linux-1.5.3/gwt-user.jar:/usr/local/home_ubuntu/crocea/script/gwt-linux-1.5.3/gwt-dev-linux.jar:/home/crocea/script/gwt-maps-1.0.2/gwt-maps.jar:/home/crocea/script/gwt-visualization-1.0.0/gwt-visualization.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" $CLASSNAME;

# 2009-4-15 link the directory into Accession/ because haploGroup is an action of controller Accession in pylons.
#cd $APPDIR/www/edu.nordborglab.Accession;
#ln -s ../$CLASSNAME ./haploGroup;
#cd ../../
